In [1]:
from reachEnvSb3 import *

[robosuite WARNING] No private macro file found! (macros.py:57)
[robosuite WARNING] It is recommended to use a private macro file (macros.py:58)
[robosuite WARNING] To setup, run: python /home/ey/rl/src/robosuite/robosuite/scripts/setup_macros.py (macros.py:59)
[robosuite WARNING] Could not import robosuite_models. Some robots may not be available. If you want to use these robots, please install robosuite_models from source (https://github.com/ARISE-Initiative/robosuite_models) or through pip install. (__init__.py:30)
[robosuite WARNING] Could not load the mink-based whole-body IK. Make sure you install related import properly, otherwise you will not be able to use the default IK controller setting for GR1 robot. (__init__.py:40)
2025-07-21 21:49:51.623298: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment va

In [ ]:
# controller_config = load_part_controller_config(default_controller="OSC_POSE")
controller_config = load_composite_controller_config(controller="BASIC")
env = ReachEnv(controller_config=controller_config)

env.test()
obs = env.reset()

for j in range(3):
    for i in range(200):
        action = np.random.uniform(low=-0.5, high=0.5, size=env.action_dim)
        obs, reward, done, _ = env.step(action)
        # if i % 20 == 0:
        #     print("reward:", reward)
        #     print("done:", done)
        if done:
            env.reset()
            break
        env.render()
env.close()

[robosuite INFO] Loading controller configuration from: /home/ey/rl/src/robosuite/robosuite/controllers/config/default/composite/basic.json (composite_controller_factory.py:121)
[robosuite WARNING] The config has defined for the controller "left", but the robot does not have this component. Skipping, but make sure this is intended.Removing the controller config for left from self.part_controller_config. (robot.py:151)
[robosuite WARNING] The config has defined for the controller "torso", but the robot does not have this component. Skipping, but make sure this is intended.Removing the controller config for torso from self.part_controller_config. (robot.py:151)
[robosuite WARNING] The config has defined for the controller "head", but the robot does not have this component. Skipping, but make sure this is intended.Removing the controller config for head from self.part_controller_config. (robot.py:151)
[robosuite WARNING] The config has defined for the controller "base", but the robot does

[chatbus] 共享内存已存在，连接成功
机械臂关节位置:
[-0.47  -1.735  2.48  -2.275 -1.59  -1.991]
机械臂关节速度:
[0. 0. 0. 0. 0. 0.]
机械臂基座序号:4
世界坐标系基座位置:
[-0.56   0.     0.912]
世界坐标系基座姿态:
[0. 0. 0. 1.]
世界坐标系基座变换:
[[ 1.     0.     0.    -0.56 ]
 [ 0.     1.     0.     0.   ]
 [ 0.     0.     1.     0.912]
 [ 0.     0.     0.     1.   ]]
机械臂末端名称:robot0_right_hand
机械臂末端序号:12
世界坐标系末端位置:
[-0.21967662 -0.02468643  1.1265394 ]
世界坐标系末端姿态:
[-9.99440888e-01  2.46934819e-02  2.25417255e-02  1.17048126e-04]
世界坐标系末端变换:
[[ 9.97764205e-01 -4.93646279e-02 -4.50524636e-02 -2.19676616e-01]
 [-4.93540741e-02 -9.98780437e-01  1.34723275e-03 -2.46864292e-02]
 [-4.50640249e-02  8.79302016e-04 -9.98983714e-01  1.12653940e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
相机坐标系目标变换:[[ 0.35561021 -0.07040647 -0.9319787  -0.42719902]
 [ 0.93385591  0.06745556  0.35123054 -0.55402014]
 [ 0.03813825 -0.99523499  0.08973738 -0.12749678]
 [ 0.          0.          0.          1.        ]]
机械臂末端名称:robot0_right_hand
机械臂末端序

[robosuite WARNING] The config has defined for the controller "left", but the robot does not have this component. Skipping, but make sure this is intended.Removing the controller config for left from self.part_controller_config. (robot.py:151)
[robosuite WARNING] The config has defined for the controller "torso", but the robot does not have this component. Skipping, but make sure this is intended.Removing the controller config for torso from self.part_controller_config. (robot.py:151)
[robosuite WARNING] The config has defined for the controller "head", but the robot does not have this component. Skipping, but make sure this is intended.Removing the controller config for head from self.part_controller_config. (robot.py:151)
[robosuite WARNING] The config has defined for the controller "base", but the robot does not have this component. Skipping, but make sure this is intended.Removing the controller config for base from self.part_controller_config. (robot.py:151)
[robosuite WARNING] Th

In [9]:
from stable_baselines3 import SAC
from stable_baselines3.common.env_util import make_vec_env
from stable_baselines3.common.vec_env import SubprocVecEnv
from stable_baselines3.common.callbacks import EvalCallback