In [4]:
# 环境测试
from reachEnv import *
from robosuite.controllers import load_controller_config
controller_config = load_controller_config(default_controller="OSC_POSE")

env = ReachEnv(controller_config=controller_config,seed=2)

env._test_matrixs()
obs = env.reset()
action = np.zeros(env.action_dim)
obs, reward, done, _ = env.step(action)

joint_positions = env.robots[0].controller.joint_pos
joint_velocities = env.robots[0].controller.joint_vel
print(joint_positions)
print(joint_velocities)
for i in range(1000):
    action = np.zeros(env.action_dim)
    obs, reward, done, _ = env.step(action)
    if i % 20 == 0:
        print("reward:", reward)
        print("done:", done)
    if done:
        break

    env.render()

env.close()


T_te:
[[ 0.98092332 -0.11038787  0.16001238 -0.05907027]
 [ 0.04493443  0.92959322  0.36583786  0.02385419]
 [-0.18913049 -0.35166882  0.91681988  0.1       ]
 [ 0.          0.          0.          1.        ]]
T_ew:
[[ 9.97764205e-01 -4.93646279e-02 -4.50524636e-02 -2.19676616e-01]
 [-4.93540741e-02 -9.98780437e-01  1.34723275e-03 -2.46864292e-02]
 [-4.50640249e-02  8.79302016e-04 -9.98983714e-01  1.12653940e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
T_bw:
[[ 1.     0.     0.    -0.56 ]
 [ 0.     1.     0.     0.   ]
 [ 0.     0.     1.     0.912]
 [ 0.     0.     0.     1.   ]]
T_cw:
[[ 0.83446533  0.54071041 -0.10630078 -0.0640051 ]
 [-0.49231741  0.8181728   0.2970132  -0.47407377]
 [ 0.24757054 -0.19551349  0.94893799  1.07483124]
 [ 0.          0.          0.          1.        ]]
T_gw:
[[ 0.87459158 -0.35976828  0.32504822 -0.29495254]
 [-0.37693194 -0.92617666 -0.0109137   0.24574215]
 [ 0.30497848 -0.11297602 -0.94563447  1.26573577]
 [ 0.       

In [3]:
# 封装环境测试
from reachEnv import *
import gym
from robosuite.wrappers import GymWrapper
from robosuite.controllers import load_controller_config
controller_config = load_controller_config(default_controller="OSC_POSE")

env = ReachEnv(controller_config=controller_config,seed=42)
env = GymWrapper(env)
env = ReachEnvWrapper(env)

print(env.action_space) 
print(env.observation_space) 


obs = env.reset()
action = np.zeros(env.action_dim)
obs, reward, terminated, truncated, info = env.step(action)

print_dict(obs)
print(reward) 
print(terminated) 
print(truncated) 
print(info) 


from skrl.envs.wrappers.torch import wrap_env
env = wrap_env(env, wrapper="gym")
print(env.num_envs)
print(env.device)
print(env.action_space) 
print(env.observation_space) 
device = env.device
obs, info = env.reset()
print(obs[0][:6])
print(obs[0][6:13])
print(obs[0][13:])


 | episode: 0 | reward: 0.0 
 | init_pos_err: 999.9 | best_pos_err: 999.9
 | init_rot_err: 999.9 | best_rot_err: 999.9
Box(-1.0, 1.0, (6,), float32)
Dict('achieved_goal': Box(-inf, inf, (6,), float32), 'desired_goal': Box(-inf, inf, (7,), float32), 'observation': Box(-inf, inf, (7,), float32))


/home/ywl/miniconda3/envs/rlreach/lib/python3.8/site-packages/gymnasium/spaces/box.py:235: UserWarning: WARN: Box low's precision lowered by casting to float32, current low.dtype=float64
  gym.logger.warn(
/home/ywl/miniconda3/envs/rlreach/lib/python3.8/site-packages/gymnasium/spaces/box.py:305: UserWarning: WARN: Box high's precision lowered by casting to float32, current high.dtype=float64
  gym.logger.warn(
/home/ywl/miniconda3/envs/rlreach/lib/python3.8/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
[skrl:INFO] Environment wrapper: Gym



 | episode: 1 | reward: 0.0 
 | init_pos_err: 0.10221054435392055 | best_pos_err: None
 | init_rot_err: 0.9851714410032052 | best_rot_err: None
achieved_goal: [-0.47  -1.735  2.48  -2.275 -1.59  -1.991]
desired_goal: [ 0.32401239 -0.53663462 -0.4098445   0.80715264  0.49264865 -0.2346934
 -0.22521308]
observation: [ 0.06437583 -0.52843084 -0.25925709 -0.59050383  0.10880428  0.79958657
  0.01132094]
-0.7499233348770508
False
False
{}
1
cuda:0
Box(-1.0, 1.0, (6,), float32)
Dict('achieved_goal': Box(-inf, inf, (6,), float32), 'desired_goal': Box(-inf, inf, (7,), float32), 'observation': Box(-inf, inf, (7,), float32))

 | episode: 2 | reward: -0.7499233348770508 
 | init_pos_err: 0.3002582422799123 | best_pos_err: 0.3002582422799123
 | init_rot_err: 1.8213017384676988 | best_rot_err: 1.8213017384676988
tensor([-0.4700, -1.7350,  2.4800, -2.2750, -1.5900, -1.9910], device='cuda:0')
tensor([-0.1498, -0.4506,  0.0283,  0.7874,  0.3076, -0.4777, -0.2391],
       device='cuda:0')
tensor([ 0.0

train

In [ ]:
from reachEnv import *
# configure and instantiate the RL trainer
cfg_trainer = {"timesteps": 100000, "headless": True}
env = generate_env()
agent = generate_agent(env)
# agent.load(path="/home/ey/rl/src/test/test/reach/runs_reach/torch/reach/25-07-14_23-32-59-260100_SAC/checkpoints/agent_1000000.pt")
trainer = SequentialTrainer(cfg=cfg_trainer, env=env, agents=[agent])
# start training
trainer.train() 

[robosuite WARNING] No private macro file found! (macros.py:53)
[robosuite WARNING] It is recommended to use a private macro file (macros.py:54)
[robosuite WARNING] To setup, run: python /home/ey/rl/wp/rl-waypoints/robosuite/robosuite/scripts/setup_macros.py (macros.py:55)
[skrl:INFO] Seed: 42
/home/ey/anaconda3/envs/rlwp1/lib/python3.8/site-packages/gymnasium/spaces/box.py:235: UserWarning: WARN: Box low's precision lowered by casting to float32, current low.dtype=float64
  gym.logger.warn(
/home/ey/anaconda3/envs/rlwp1/lib/python3.8/site-packages/gymnasium/spaces/box.py:305: UserWarning: WARN: Box high's precision lowered by casting to float32, current high.dtype=float64
  gym.logger.warn(
/home/ey/anaconda3/envs/rlwp1/lib/python3.8/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
[skrl:INFO] Environment wrapper: Gym



 | episode: 0 | reward: 0.0 
 | init_pos_err: 999.9 | best_pos_err: 999.9
 | init_rot_err: 999.9 | best_rot_err: 999.9

 | episode: 1 | reward: 0.0 
 | init_pos_err: 0.10221054435392055 | best_pos_err: None
 | init_rot_err: 0.9851714410032052 | best_rot_err: None
  0%|          | 199/1500000 [00:01<2:34:51, 161.41it/s]
 | episode: 2 | reward: -1822.4819718707192 
 | init_pos_err: 0.3002582422799123 | best_pos_err: 0.3033116488327602
 | init_rot_err: 1.8213017384676988 | best_rot_err: 0.7525134658226186
  0%|          | 383/1500000 [00:02<2:36:15, 159.95it/s]
 | episode: 3 | reward: -1820.7885875001234 
 | init_pos_err: 0.3669444260223481 | best_pos_err: 0.33279350243345834
 | init_rot_err: 1.232080099080897 | best_rot_err: 0.31112649592700437
  0%|          | 584/1500000 [00:04<2:34:19, 161.93it/s]
 | episode: 4 | reward: -1723.2968593323824 
 | init_pos_err: 0.30244464759245926 | best_pos_err: 0.15265176533460145
 | init_rot_err: 1.382839031837748 | best_rot_err: 0.8441545253889949
 

eval

In [2]:
from reachEnv import *
test_env = generate_env()
test_agent = generate_agent(test_env)
test_agent.load(path="/home/ey/rl/src/test/test/reach/runs_reach/torch/reach/25-07-16_11-26-47-965794_SAC/checkpoints/agent_500000.pt")
cfg_trainer = {"timesteps": 3000, "headless": False}
test_trainer = SequentialTrainer(cfg=cfg_trainer, env=test_env, agents=[test_agent])
test_trainer.eval()

/home/ey/anaconda3/envs/rlwp1/lib/python3.8/site-packages/gymnasium/spaces/box.py:235: UserWarning: WARN: Box low's precision lowered by casting to float32, current low.dtype=float64
  gym.logger.warn(
/home/ey/anaconda3/envs/rlwp1/lib/python3.8/site-packages/gymnasium/spaces/box.py:305: UserWarning: WARN: Box high's precision lowered by casting to float32, current high.dtype=float64
  gym.logger.warn(
/home/ey/anaconda3/envs/rlwp1/lib/python3.8/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
[skrl:INFO] Environment wrapper: Gym



 | episode: 0 | reward: 0.0 
 | init_pos_err: 0.10221054435392055 | best_pos_err: 999.9
 | init_rot_err: 0.9851714410032052 | best_rot_err: 999.9

 | episode: 1 | reward: 0.0 
 | init_pos_err: 0.3002582422799123 | best_pos_err: None
 | init_rot_err: 1.8213017384676988 | best_rot_err: None
  7%|▋         | 196/3000 [00:03<00:49, 56.41it/s]
 | episode: 2 | reward: -1923.1646486983286 
 | init_pos_err: 0.3669444260223481 | best_pos_err: 0.30476555550509793
 | init_rot_err: 1.232080099080897 | best_rot_err: 0.7758139409305177
 13%|█▎        | 395/3000 [00:07<00:44, 58.60it/s]
 | episode: 3 | reward: -1523.0748880159551 
 | init_pos_err: 0.30244464759245926 | best_pos_err: 0.2113564478934391
 | init_rot_err: 1.382839031837748 | best_rot_err: 0.11464697796822716
 20%|█▉        | 595/3000 [00:11<00:38, 62.14it/s]
 | episode: 4 | reward: -2010.3532508739204 
 | init_pos_err: 0.31965059830180154 | best_pos_err: 0.30301159209568274
 | init_rot_err: 1.4452874750326594 | best_rot_err: 1.389098465

In [ ]:

        # reward_value -= 0.4 * self.rot_err
        # reward_value += 0.1 * (1 - np.tanh(self.rot_err)) 
        # reward_value += 1.0 if (self.rot_err < rot_err_threshold) else 0.0
        # reward_value -= -1.0 if (self.rot_err > self.rot_err) else 0.0

t:
 [[ 0.22157936  0.7135978  -0.66459068 -0.12545988]
 [-0.41534735  0.68568362  0.59776631  0.45071431]
 [ 0.88226366  0.1435833   0.44832429  1.16599697]
 [ 0.          0.          0.          1.        ]]
t_new:
 [[-0.10068928  0.78959311 -0.60531346 -0.20073581]
 [-0.46446219  0.50073545  0.73043746  0.72114289]
 [ 0.87985029  0.35469244  0.31631745  1.30519334]
 [ 0.          0.          0.          1.        ]]
pos_err: 0.3133268460484926
rot_err: 0.34028718411841424
t:
 [[ 0.22157936  0.7135978  -0.66459068 -0.12545988]
 [-0.41534735  0.68568362  0.59776631  0.45071431]
 [ 0.88226366  0.1435833   0.44832429  1.16599697]
 [ 0.          0.          0.          1.        ]]
t_new:
 [[ 0.11892323  0.35110476 -0.92875331 -0.39060971]
 [-0.52855225  0.8142294   0.24013123  0.67041999]
 [ 0.84052946  0.46233748  0.282408    1.22666598]
 [ 0.          0.          0.          1.        ]]
pos_err: 0.3496508991848011
rot_err: 0.5052767374259578
t:
 [[ 0.22157936  0.7135978  -0.66459068 -